name: Sync Toast Docs

on:
  push:
    branches: [main]
    paths:
      - packages/toast/docs/**

jobs:
  sync:
    uses: ./.github/workflows/_sync-docs.yml
    with:
      package: toast
    secrets: inherit
